sudo: false
language: python
python:
  - 2.7
addons:
  apt:
    packages:
      - libspatialite-dev
install:
  - pip install -i http://pypi.pacificclimate.org/simple/ -r requirements.txt -r test_requirements.txt
  - pip install .
script: py.test -v --tb=short tests
