@Library('pcic-pipeline-library@python-test-suite-fixes')_


node {
    stage('Code Collection') {
        collectCode()
    }

    stage('Python Test Suite') {
        def pyImage = 'pcic/test-env:python3.6'
        def requirements = ['requirements.txt', 'test_requirements.txt']
        def pytestArgs = '-vv --tb=short tests'
        def options = [pythonVersion: 2, containerData: "tester", selfInstall: false]

        runPythonTestSuite(pyImage, requirements, pytestArgs, options)
    }

    stage('Clean Workspace') {
        cleanWs()
    }

    stage('Recollect Code') {
        collectCode()
    }

    if (isPypiPublishable()) {
        stage('Push to PYPI') {
            publishPythonPackage('pcic/test-env:python3.6', 'PCIC_PYPI_CREDS')
        }
    }

    stage('Clean Workspace') {
        cleanWs()
    }
}
