@Library('pcic-pipeline-library')_


node {
    stage('Code Collection') {
        collectCode()
    }

    stage('Python Test Suite') {
        def pyImage = 'pcic/pdp_util-test-env:python-2.7'
        def requirements = ['requirements.txt', 'test_requirements.txt']
        def pytestArgs = '-vv --tb=short tests'
        def options = [pythonVersion: 2]

        runPythonTestSuite(pyImage, requirements, pytestArgs, options)
    }

    stage('Clean Workspace') {
        cleanWs()
    }

    stage('Recollect Code') {
        collectCode()
    }

    if (isPypiPublishable()) {
        stage('Push to PYPI') {
            publishPythonPackage('pcic/pdp_util-test-env:python-2.7', 'PCIC_PYPI_CREDS')
        }
    }

    stage('Clean Workspace') {
        cleanWs()
    }
}
