name: Black check

on: push

jobs:
  black:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          version: "23.11.0"
          options: "--check"
          src: "."
