name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.8"
          # TODO: Test with other Pythons
#          - "3.9"
#          - "3.10"
#          - "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          # Add legacy repo and update
          sudo apt-get install -y curl ca-certificates gnupg
          sudo curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo echo 'deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          # Install postgresql extensions
          sudo apt-get install postgresql-plpython3-14 postgresql-14-postgis-3
          # Install remaining dependencies
          sudo apt-get install libhdf5-serial-dev libnetcdf-dev libspatialite-dev libgdal-dev 

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Installing this project is tricky, due to its dependency on GDAL 3.0.4.
      # For an explanation, see the README.
      - name: Install project
        run: |
          # Pre-install initial packages (pip, setuptools, numpy) 
          poetry install --only initial
          # Install gdal using pip3 into the Poetry virtualenv
          poetry run pip3 install gdal==3.0.4
          # Install rest of project          
          poetry install --without black

      - name: Test with pytest (full)
        if: github.ref == 'refs/heads/master'
        run: |
          poetry run pytest -m "not online" -v --tb=short tests

      - name: Test with pytest (fast)
        if: github.ref != 'refs/heads/master'
        run: |
          poetry run pytest -m "not online and not slow" -v --tb=short tests
